# Asciidoctor settings
asciidoc:
  index:
    file: index.adoc
  multipage_level: 2

# Build directories
build:
  dir: /tmp/build
  html:
    dir: /tmp/build/html

# Enable extensions
extensions:
  enable:
    - IfChecker
    - IdChecker
    - LinkChecker
    - PatternBlacklist

processes:
  pre:
    enable:
      - CombineAndTranspileJS
  post:
    enable:
      - CompileSearchIndex
      - Rename
      - HTMLTest
      - CodeRayStyleCopy

checkers:
  pattern:
    blacklist: blacklist.txt

search:
  index:
    file: lunrindex.json
  db:
    file: lunrdb.json
  exclude:
    - docinfo*.html
    - index.html
    - Imprint.html
    - ContactUs.html

log:
  file: /tmp/log.json

toc:
  json_file: toc.json
  html_file: toc.html
