name: Build Template

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOOLCHAIN_PATH: 'toolchain'

    steps:
    - name: Extract branch name
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "##[set-output name=pr;]pr$(echo ${GITHUB_REF} | cut -d'/' -f3)"
      id: extract_branch

    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'

    - name: Setup
      run: bash toolchain/setup/setup.sh

    - name: Test
      run: |
        rake docs:test

    - name: Pre-processing
      if: always()
      run: |
        rake docs:pre

    - name: Build
      run: |
        rake docs:build

    - name: Post-processing
      if: always()
      run: |
        rake docs:post
        cp -r /tmp/build/html public/

    - name: Upload as Artifact
      uses: actions/upload-artifact@master
      with:
        name: built-webpage-${{steps.extract_branch.outputs.branch}}
        path: public/

    - name: Prepend branch name
      if: github.event_name == 'push' && steps.extract_branch.outputs.branch != 'master'
      run: |
        mkdir -p branches/${{ steps.extract_branch.outputs.branch }}
        mv public/* branches/${{ steps.extract_branch.outputs.branch }}
        mv branches/${{ steps.extract_branch.outputs.branch }} public/

    - name: Prepend pull request number
      if: github.event_name == 'pull_request'
      run: |
        mkdir -p branches/${{ steps.extract_branch.outputs.pr }}
        mv public/* branches/${{ steps.extract_branch.outputs.pr }}
        mv branches/${{ steps.extract_branch.outputs.pr }} public/

    - name: Deploy
      uses: wirecard/s3-deploy@v1
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        SRC_DIR: public/
        DST_DIR: docs-template/

  frontend:
    runs-on: ubuntu-latest
    needs: build
    services:
      nginx:
        image: nginx
        ports:
          - 8888:80
        volumes:
          - ${{ github.workspace }}/public:/usr/share/nginx/html:ro
      hub:
        image: selenium/hub:3.14.0-gallium
        ports:
          - "4444:4444"
      firefox:
        image: selenium/node-firefox:3.14.0-gallium
        volumes:
          - /dev/shm:/dev/shm
        env:
          HUB_HOST: hub
      chrome:
        image: selenium/node-chrome:3.14.0-gallium
        volumes:
          - /dev/shm:/dev/shm
        env:
          HUB_HOST: hub

    steps:
    - name: Extract branch name
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "##[set-output name=pr;]pr$(echo ${GITHUB_REF} | cut -d'/' -f3)"
      id: extract_branch

    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - uses: actions/download-artifact@v1
      with:
        name: built-webpage-${{steps.extract_branch.outputs.branch}}
        path: public

    - name: Run e2e tests
      run: |
        cd end2end
        rake selenium:test

