name: Build Template

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOOLCHAIN_PATH: 'toolchain'

    steps:
    - name: Extract build name
      shell: bash
      run: echo "::set-output name=build_name::$(bash .scripts/extract_build_name.sh)"
      id: extract

    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'

    - name: Setup
      run: bash toolchain/setup/setup.sh

    - name: Test
      run: |
        rake docs:test

    - name: Pre-processing
      if: always()
      run: |
        rake docs:pre

    - name: Build
      run: |
        rake docs:build

    - name: Post-processing
      if: always()
      run: |
        rake docs:post
        cp -r /tmp/build/html public/

    - name: Upload as Artifact
      uses: actions/upload-artifact@master
      with:
        name: built-webpage-${{ steps.extract.outputs.build_name }}
        path: public/

    - name: Prepend build name
      if: steps.init.outputs.branch != 'master'
      run: |
        mkdir -p branches/${{ steps.extract.outputs.build_name }}
        mv public/* branches/${{ steps.extract.outputs.build_name }}
        mv branches/${{ steps.extract.outputs.build_name }} public/

  frontend:
    runs-on: ubuntu-latest
    needs: build
    env:
      TOOLCHAIN_PATH: 'toolchain'
    services:
      nginx:
        image: nginx
        ports:
          - 8888:80
        volumes:
          - ${{ github.workspace }}/public:/usr/share/nginx/html:ro
      hub:
        image: selenium/hub:3.14.0-gallium
        ports:
          - "4444:4444"
      firefox:
        image: selenium/node-firefox:3.14.0-gallium
        volumes:
          - /dev/shm:/dev/shm
        env:
          HUB_HOST: hub
      chrome:
        image: selenium/node-chrome:3.14.0-gallium
        volumes:
          - /dev/shm:/dev/shm
        env:
          HUB_HOST: hub

    steps:
    - name: Extract build name
      shell: bash
      run: echo "::set-output name=build_name::$(bash .scripts/extract_build_name.sh)"
      id: extract

    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'

    - name: Setup
      run: bash toolchain/setup/setup.sh

    - uses: actions/download-artifact@v1
      with:
        name: built-webpage-${{ steps.extract.outputs.build_name }}
        path: public

    - name: Run e2e tests
      run: |
        cd end2end
        rake selenium:test

