name: End 2 End Testing

on: [push, pull_request]

jobs:
  frontend:
    runs-on: ubuntu-latest
    needs: build
    env:
      TOOLCHAIN_PATH: 'toolchain'
    services:
      nginx:
        image: nginx
        ports:
          - 8888:80
        volumes:
          - ${{ github.workspace }}/public:/usr/share/nginx/html:ro
      hub:
        image: selenium/hub:3.14.0-gallium
        ports:
          - "4444:4444"
      firefox:
        image: selenium/node-firefox:3.14.0-gallium
        volumes:
          - /dev/shm:/dev/shm
        env:
          HUB_HOST: hub
      chrome:
        image: selenium/node-chrome:3.14.0-gallium
        volumes:
          - /dev/shm:/dev/shm
        env:
          HUB_HOST: hub

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Extract build name
      shell: bash
      run: echo "::set-output name=build_name::$(bash .scripts/extract_build_name.sh)"
      id: extract

    - name: Setup Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'

    - name: Setup
      run: bash toolchain/setup/setup.sh

    - name: Build
      run: |
        rake docs:all

    # - name: Start Selenium Hub
    #   run: rake selenium:up

    - name: Run end2end tests
      run: |
        cd end2end
        rake selenium:test

    # - name: Destroy Selenium Hub
    #   run: rake selenium:down
