name: End 2 End Testing

on: [push, pull_request]

jobs:
  frontend:
    runs-on: ubuntu-latest
    env:
      TOOLCHAIN_PATH: 'toolchain'

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Extract build name
      shell: bash
      run: echo "::set-output name=build_name::$(bash .scripts/extract_build_name.sh)"
      id: extract

    - name: Setup Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'

    - name: Setup
      run: bash toolchain/setup/setup.sh

    - name: Build docs
      run: rake docs:all

    - name: cd end2end
      run: cd end2end

    - name: Start Selenium Hub
      run: rake selenium:up

    - name: Run end2end tests
      run: rake selenium:test

    - name: Destroy Selenium Hub
      run: rake selenium:down
